<a href="https://colab.research.google.com/github/Oksana0020/DL-with-PyTorch/blob/main/Lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Tensor Operations, Gradients, and GPU Practice

In [2]:
# Task 1: Create Tensors and Perform Matrix Operations
import torch
import torch.nn as nn
import torch.optim as optim
matrix_3x3 = torch.tensor([[1.0, 2.0, 3.0],
                           [4.0, 5.0, 6.0],
                           [7.0, 8.0, 9.0]])
vector_3x1 = torch.tensor([[1.0], [2.0], [3.0]])

# Perform matrix multiplication
result = torch.mm(matrix_3x3, vector_3x1)
print(f"Matrix multiplication result:\n{result}")
print(f"Result shape: {result.shape}")

# Try reverse multiplication
try:
    reverse_result = torch.mm(vector_3x1, matrix_3x3)
except RuntimeError as e:
    print(f"Error in reverse multiplication: {e}")



Matrix multiplication result:
tensor([[14.],
        [32.],
        [50.]])
Result shape: torch.Size([3, 1])
Error in reverse multiplication: mat1 and mat2 shapes cannot be multiplied (3x1 and 3x3)


In [3]:
# Task 2: Reshape and Broadcast Tensors
tensor1D = torch.arange(6)
print(f"Original 1D tensor: {tensor1D}")

reshaped_tensor = tensor1D.view(2, 3)
print(f"Reshaped 2x3 tensor:\n{reshaped_tensor}")

tensor2D = torch.tensor([[1], [2]])
print(f"Second tensor shape: {tensor2D.shape}")

# Broadcasting example
broadcasted_sum = reshaped_tensor + tensor2D
print(f"Result after broadcasting:\n{broadcasted_sum}")



Original 1D tensor: tensor([0, 1, 2, 3, 4, 5])
Reshaped 2x3 tensor:
tensor([[0, 1, 2],
        [3, 4, 5]])
Second tensor shape: torch.Size([2, 1])
Result after broadcasting:
tensor([[1, 2, 3],
        [5, 6, 7]])


In [6]:
# Task 3: Move Tensors Between CPU and GPU
# Create a large tensor
import time
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
large_tensor = torch.rand((1000, 1000))

# Time the operation on CPU
start_cpu = time.time()
result_cpu = large_tensor ** 2
end_cpu = time.time()
cpu_time = end_cpu - start_cpu

# Move to GPU if available
if torch.cuda.is_available():
    large_tensor_gpu = large_tensor.to(device)

    # Time the operation on GPU
    start_gpu = time.time()
    result_gpu = large_tensor_gpu ** 2
    # Ensure operation is complete before timing
    torch.cuda.synchronize()
    end_gpu = time.time()
    gpu_time = end_gpu - start_gpu

    print(f"CPU time: {cpu_time:.6f} seconds")
    print(f"GPU time: {gpu_time:.6f} seconds")
    print(f"Speedup: {cpu_time/gpu_time:.2f}x")
else:
    print(f"CPU time: {cpu_time:.6f} seconds")
    print("GPU not available for comparison")



CPU time: 0.003676 seconds
GPU not available for comparison


In [5]:
# Task 4: Define Custom Functions and Utilize Autograd
# Create tensor with gradient tracking
x_tensor = torch.tensor([2.0, 3.0, 4.0], requires_grad=True)

# Define and apply custom function
def custom_function(x):
    return x**3 + 2*x**2

y_tensor = custom_function(x_tensor)
print(f"Function output: {y_tensor}")

# Sum to get scalar for backward function
y_sum = y_tensor.sum()

# Compute gradients
y_sum.backward()

# Print gradients
print(f"Input values: {x_tensor}")
print(f"Computed gradients: {x_tensor.grad}")
print(f"Expected gradients (3x² + 4x): {3*x_tensor**2 + 4*x_tensor}")

Function output: tensor([16., 45., 96.], grad_fn=<AddBackward0>)
Input values: tensor([2., 3., 4.], requires_grad=True)
Computed gradients: tensor([20., 39., 64.])
Expected gradients (3x² + 4x): tensor([20., 39., 64.], grad_fn=<AddBackward0>)
